local M = {}

local function style(enabled, value)
    return enabled and value or nil
end

local function merge(base, extra)
    return vim.tbl_extend('force', base, extra or {})
end

M.get = function(colors, opts)
    local bg = opts.transparent and colors.none or colors.bg
    local bg_nc = opts.transparent and colors.none or colors.bg_nc
    local inverse = opts.inverse
    local comments = merge({
        fg = colors.fg,
        bg = bg,
        italic = opts.italic,
        reverse = inverse,
    }, opts.styles.comments)

    return {
        Normal = { fg = colors.fg, bg = bg },
        NormalNC = { fg = colors.fg, bg = opts.dim_inactive and bg_nc or bg },
        NormalFloat = { fg = colors.fg, bg = colors.gray_28 },
        FloatBorder = { fg = colors.ui_6, bg = colors.gray_28 },
        FloatTitle = { fg = colors.fg, bg = colors.gray_28, bold = opts.bold },
        ColorColumn = { fg = colors.orange, bg = colors.orange_bg },
        Conceal = { fg = colors.gray_01, bg = bg, bold = opts.bold },
        Cursor = { reverse = true },
        CursorColumn = { bg = colors.ui_1 },
        CursorLine = { bg = colors.ui_1 },
        CursorLineNr = { fg = colors.gray_05, bg = colors.ui_1, bold = opts.bold },
        Directory = { fg = colors.fg, bg = bg, bold = opts.bold },
        EndOfBuffer = { fg = colors.gray_01, bg = bg },
        ErrorMsg = { fg = colors.fg, bg = bg, bold = opts.bold, reverse = inverse },
        FoldColumn = { fg = colors.gray_14, bg = bg },
        Folded = { fg = colors.gray_05, bg = colors.ui_2, italic = opts.italic },
        LineNr = { fg = colors.gray_15, bg = bg },
        MatchParen = { fg = colors.blue, bg = colors.blue_bg, bold = opts.bold },
        ModeMsg = { fg = colors.blue, bg = bg, bold = opts.bold },
        MoreMsg = { fg = colors.blue, bg = bg, bold = opts.bold },
        NonText = { fg = colors.gray_01, bg = bg },
        Question = { fg = colors.green, bg = bg, bold = opts.bold },
        SignColumn = { fg = colors.blue, bg = bg },
        SpecialKey = { fg = colors.gray_10, bg = bg },
        StatusLine = { fg = colors.black, bg = bg, underline = true },
        StatusLineNC = { fg = colors.ui_7, bg = bg, underline = true, italic = opts.italic },
        Substitute = { fg = colors.black, bg = colors.yellow, reverse = inverse },
        TabLine = { fg = colors.ui_5, bg = bg },
        TabLineFill = { bg = bg },
        TabLineSel = { fg = colors.gray_28, bg = colors.ui_3, bold = opts.bold },
        Title = { fg = colors.fg, bg = bg, bold = opts.bold },
        VertSplit = { fg = colors.ui_5, bg = bg },
        Visual = { reverse = inverse },
        VisualNOS = { reverse = inverse },
        WarningMsg = { fg = colors.red, bg = bg, bold = opts.bold },
        Whitespace = { fg = colors.gray_20, bg = bg },
        WildMenu = { fg = colors.blue, bg = colors.white, bold = opts.bold, reverse = inverse },
        WinSeparator = { fg = colors.ui_5, bg = bg },

        Search = { fg = colors.black, bg = colors.yellow },
        IncSearch = { fg = colors.black, bg = colors.yellow, reverse = inverse },
        CurSearch = { fg = colors.black, bg = colors.none, bold = opts.bold, reverse = inverse },

        Comment = comments,
        Constant = { fg = colors.fg, bg = bg, bold = opts.bold },
        String = { fg = colors.fg, bg = bg, italic = opts.italic },
        Character = { fg = colors.fg, bg = bg, italic = opts.italic },
        Number = { fg = colors.fg, bg = bg, italic = opts.italic },
        Boolean = { fg = colors.fg, bg = bg, bold = opts.bold },
        Float = { fg = colors.fg, bg = bg, italic = opts.italic },
        Identifier = { fg = colors.fg, bg = bg, italic = opts.italic },
        Function = merge({ fg = colors.fg, bg = bg, italic = opts.italic }, opts.styles.functions),
        Statement = { fg = colors.fg, bg = bg, bold = opts.bold },
        Conditional = { fg = colors.fg, bg = bg, bold = opts.bold },
        Repeat = { fg = colors.fg, bg = bg, bold = opts.bold },
        Label = { fg = colors.fg, bg = bg, bold = opts.bold },
        Operator = { fg = colors.fg, bg = bg },
        Keyword = merge({ fg = colors.fg, bg = bg, bold = opts.bold }, opts.styles.keywords),
        Exception = { fg = colors.fg, bg = bg, bold = opts.bold },
        PreProc = { fg = colors.fg, bg = bg, bold = opts.bold },
        Include = { fg = colors.fg, bg = bg, italic = opts.italic },
        Define = { fg = colors.fg, bg = bg, bold = opts.bold },
        Macro = { fg = colors.fg, bg = bg, bold = opts.bold },
        PreCondit = { fg = colors.gray_01, bg = bg, italic = opts.italic },
        Type = merge({ fg = colors.fg, bg = bg, bold = opts.bold }, opts.styles.types),
        StorageClass = { fg = colors.fg, bg = bg, bold = opts.bold },
        Structure = { fg = colors.fg, bg = bg, bold = opts.bold },
        Typedef = { fg = colors.fg, bg = bg, italic = opts.italic },
        Special = { fg = colors.fg, bg = bg, italic = opts.italic },
        Underlined = { fg = colors.fg, bg = bg, underline = true },
        Error = { fg = colors.fg, bg = bg, bold = opts.bold, reverse = inverse },
        Todo = {
            fg = colors.fg,
            bg = bg,
            bold = opts.bold,
            italic = opts.italic,
            reverse = inverse,
        },

        Pmenu = { fg = colors.fg, bg = colors.ui_5 },
        PmenuSel = { fg = colors.white, bg = colors.fg, bold = opts.bold },
        PmenuKind = { fg = colors.blue, bg = colors.ui_5 },
        PmenuExtra = { fg = colors.gray_10, bg = colors.ui_5 },
        PmenuSbar = { bg = colors.ui_5 },
        PmenuThumb = { bg = colors.fg },

        DiffAdd = { fg = colors.green, bg = colors.green_bg },
        DiffChange = { fg = colors.blue, bg = colors.blue_bg },
        DiffDelete = { fg = colors.red, bg = colors.red_bg },
        DiffText = { fg = colors.blue, bg = colors.blue_bg, underline = true },
        Added = { fg = colors.green, bg = bg },
        Changed = { fg = colors.blue, bg = bg },
        Removed = { fg = colors.red, bg = bg },

        DiagnosticError = { fg = colors.red, bg = bg },
        DiagnosticWarn = { fg = colors.orange, bg = bg },
        DiagnosticInfo = { fg = colors.blue, bg = bg },
        DiagnosticHint = { fg = colors.green, bg = bg },
        DiagnosticOk = { fg = colors.green, bg = bg },
        DiagnosticVirtualTextError = { fg = colors.red, bg = colors.bg_error },
        DiagnosticVirtualTextWarn = { fg = colors.orange, bg = colors.orange_bg },
        DiagnosticVirtualTextInfo = { fg = colors.blue, bg = colors.blue_bg_soft },
        DiagnosticVirtualTextHint = { fg = colors.green, bg = colors.green_bg },
        DiagnosticUnderlineError = { sp = colors.red, undercurl = true },
        DiagnosticUnderlineWarn = { sp = colors.orange, undercurl = true },
        DiagnosticUnderlineInfo = { sp = colors.blue, undercurl = true },
        DiagnosticUnderlineHint = { sp = colors.green, undercurl = true },
        DiagnosticFloatingError = { fg = colors.red, bg = colors.gray_28 },
        DiagnosticFloatingWarn = { fg = colors.orange, bg = colors.gray_28 },
        DiagnosticFloatingInfo = { fg = colors.blue, bg = colors.gray_28 },
        DiagnosticFloatingHint = { fg = colors.green, bg = colors.gray_28 },
        DiagnosticSignError = { fg = colors.red, bg = bg },
        DiagnosticSignWarn = { fg = colors.orange, bg = bg },
        DiagnosticSignInfo = { fg = colors.blue, bg = bg },
        DiagnosticSignHint = { fg = colors.green, bg = bg },

        LspReferenceText = { bg = colors.ui_2 },
        LspReferenceRead = { bg = colors.ui_2 },
        LspReferenceWrite = { bg = colors.ui_2, underline = true },
        LspInlayHint = { fg = colors.gray_15, bg = colors.ui_2 },
        LspCodeLens = { fg = colors.gray_15, bg = bg },
        LspCodeLensSeparator = { fg = colors.gray_20, bg = bg },

        SpellBad = { sp = colors.blue, undercurl = true },
        SpellCap = { sp = colors.red, undercurl = true },
        SpellLocal = { sp = colors.green, undercurl = true },
        SpellRare = { sp = colors.magenta, undercurl = true },

        ['@comment'] = comments,
        ['@comment.todo'] = { link = 'Todo' },
        ['@comment.note'] = { link = 'Todo' },
        ['@comment.warning'] = { link = 'WarningMsg' },
        ['@comment.error'] = { link = 'ErrorMsg' },
        ['@constant'] = { link = 'Constant' },
        ['@constant.builtin'] = { fg = colors.fg, bg = bg, bold = opts.bold },
        ['@constructor'] = { link = 'Type' },
        ['@function'] = { link = 'Function' },
        ['@function.builtin'] = { link = 'Function' },
        ['@function.call'] = { link = 'Function' },
        ['@keyword'] = { link = 'Keyword' },
        ['@keyword.function'] = { link = 'Keyword' },
        ['@keyword.operator'] = { link = 'Operator' },
        ['@label'] = { link = 'Label' },
        ['@markup.heading'] = { link = 'Title' },
        ['@markup.italic'] = { italic = style(opts.italic, true) },
        ['@markup.link'] = { fg = colors.blue, underline = true },
        ['@markup.raw'] = { fg = colors.fg, bg = colors.ui_2 },
        ['@markup.strong'] = { bold = style(opts.bold, true) },
        ['@markup.underline'] = { underline = true },
        ['@module'] = { fg = colors.fg, bg = bg, italic = opts.italic },
        ['@number'] = { link = 'Number' },
        ['@operator'] = { link = 'Operator' },
        ['@property'] = { fg = colors.fg, bg = bg },
        ['@punctuation'] = { fg = colors.fg, bg = bg },
        ['@string'] = { link = 'String' },
        ['@tag'] = { fg = colors.fg, bg = bg, bold = opts.bold },
        ['@tag.attribute'] = { fg = colors.fg, bg = bg, italic = opts.italic },
        ['@type'] = { link = 'Type' },
        ['@variable'] = { fg = colors.fg, bg = bg },
        ['@variable.builtin'] = { fg = colors.fg, bg = bg, italic = opts.italic },
        ['@variable.parameter'] = { fg = colors.fg, bg = bg, italic = opts.italic },
    }
end

return M
