local util = require('lumiere.util')

local M = {}

M.get = function(colors, opts)
    local bg = opts.transparent and colors.none or colors.bg
    local heading_bg = {
        util.blend(colors.blue_bg_soft, colors.bg, 0.45),
        util.blend(colors.green_bg, colors.bg, 0.25),
        util.blend(colors.yellow_bg, colors.bg, 0.45),
        util.blend(colors.magenta_bg, colors.bg, 0.25),
        util.blend(colors.orange_bg, colors.bg, 0.22),
        util.blend(colors.gray_26, colors.bg, 0.55),
    }

    local groups = {
        ['@annotation'] = { link = 'PreProc' },
        ['@attribute'] = { link = 'PreProc' },
        ['@boolean'] = { link = 'Boolean' },
        ['@character'] = { link = 'Character' },
        ['@character.printf'] = { link = 'Special' },
        ['@character.special'] = { link = 'Special' },
        ['@comment'] = { link = 'Comment' },
        ['@comment.todo'] = { link = 'Todo' },
        ['@comment.note'] = { link = 'Todo' },
        ['@comment.warning'] = { link = 'WarningMsg' },
        ['@comment.error'] = { link = 'ErrorMsg' },
        ['@constant'] = { link = 'Constant' },
        ['@constant.builtin'] = { fg = colors.fg, bg = bg, bold = opts.bold },
        ['@constant.macro'] = { link = 'Define' },
        ['@constructor'] = { link = 'Type' },
        ['@diff.delta'] = { link = 'DiffChange' },
        ['@diff.minus'] = { link = 'DiffDelete' },
        ['@diff.plus'] = { link = 'DiffAdd' },
        ['@function'] = { link = 'Function' },
        ['@function.builtin'] = { link = 'Function' },
        ['@function.call'] = { link = 'Function' },
        ['@function.macro'] = { link = 'Macro' },
        ['@function.method'] = { link = 'Function' },
        ['@function.method.call'] = { link = 'Function' },
        ['@keyword'] = { link = 'Keyword' },
        ['@keyword.conditional'] = { link = 'Keyword' },
        ['@keyword.coroutine'] = { link = 'Keyword' },
        ['@keyword.debug'] = { link = 'Debug' },
        ['@keyword.directive'] = { link = 'PreProc' },
        ['@keyword.directive.define'] = { link = 'Define' },
        ['@keyword.exception'] = { fg = colors.red, bg = bg, bold = opts.bold },
        ['@keyword.function'] = { link = 'Keyword' },
        ['@keyword.import'] = { link = 'Keyword' },
        ['@keyword.operator'] = { link = 'Operator' },
        ['@keyword.repeat'] = { link = 'Keyword' },
        ['@keyword.return'] = { link = 'Keyword' },
        ['@keyword.storage'] = { link = 'StorageClass' },
        ['@label'] = { link = 'Label' },
        ['@markup'] = {},
        ['@markup.heading'] = { link = 'Title' },
        ['@markup.italic'] = { italic = util.style(opts.italic, true) },
        ['@markup.link'] = { fg = colors.blue, underline = true },
        ['@markup.link.label'] = { link = 'Special' },
        ['@markup.link.label.symbol'] = { link = 'Identifier' },
        ['@markup.link.url'] = { link = 'Underlined' },
        ['@markup.list'] = { fg = colors.blue, bg = bg },
        ['@markup.list.checked'] = { fg = colors.green, bg = bg },
        ['@markup.list.markdown'] = { fg = colors.orange, bg = bg, bold = opts.bold },
        ['@markup.list.unchecked'] = { fg = colors.blue, bg = bg },
        ['@markup.math'] = { link = 'Special' },
        ['@markup.raw'] = { bg = colors.ui_2 },
        ['@markup.raw.block'] = { bg = colors.ui_2 },
        ['@markup.raw.block.markdown'] = { bg = colors.ui_2 },
        ['@markup.raw.markdown_inline'] = { fg = colors.fg, bg = colors.ui_2 },
        ['@markup.strikethrough'] = { strikethrough = true },
        ['@markup.strong'] = { bold = util.style(opts.bold, true) },
        ['@markup.underline'] = { underline = true },
        ['@module'] = { fg = colors.fg, bg = bg, italic = opts.italic },
        ['@module.builtin'] = { fg = colors.fg, bg = bg, italic = opts.italic },
        ['@namespace.builtin'] = { link = '@variable.builtin' },
        ['@none'] = {},
        ['@number'] = { link = 'Number' },
        ['@number.float'] = { link = 'Float' },
        ['@operator'] = { link = 'Operator' },
        ['@property'] = { fg = colors.fg, bg = bg },
        ['@punctuation'] = { fg = colors.fg, bg = bg },
        ['@punctuation.bracket'] = { fg = colors.gray_05, bg = bg },
        ['@punctuation.delimiter'] = { fg = colors.gray_05, bg = bg },
        ['@punctuation.special'] = { fg = colors.gray_05, bg = bg },
        ['@punctuation.special.markdown'] = { fg = colors.orange, bg = bg },
        ['@string'] = { link = 'String' },
        ['@string.documentation'] = { fg = colors.gray_10, bg = bg, italic = opts.italic },
        ['@string.escape'] = { fg = colors.magenta, bg = bg },
        ['@string.regexp'] = { fg = colors.blue, bg = bg },
        ['@tag'] = { fg = colors.fg, bg = bg, bold = opts.bold },
        ['@tag.attribute'] = { fg = colors.fg, bg = bg, italic = opts.italic },
        ['@tag.delimiter'] = { fg = colors.gray_05, bg = bg },
        ['@type'] = { link = 'Type' },
        ['@type.builtin'] = { link = 'Type' },
        ['@type.definition'] = { link = 'Typedef' },
        ['@type.qualifier'] = { link = 'Keyword' },
        ['@variable'] = { fg = colors.fg, bg = bg },
        ['@variable.builtin'] = { fg = colors.fg, bg = bg, italic = opts.italic },
        ['@variable.member'] = { fg = colors.fg, bg = bg },
        ['@variable.parameter'] = { fg = colors.fg, bg = bg, italic = opts.italic },
        ['@variable.parameter.builtin'] = { fg = colors.gray_10, bg = bg, italic = opts.italic },
    }

    for level, level_bg in ipairs(heading_bg) do
        groups['@markup.heading.' .. level .. '.markdown'] = {
            fg = colors.fg,
            bg = level_bg,
            bold = opts.bold,
        }
    end

    return groups
end

return M
